# kafka:
#   brokers:
#     - "kafka:9092"
#   username: "dev-user"
#   password: "dev-password"
#   topic: "latestMsgToRedis"
#   retries: 10
#   producer_return_successes: true
# log:
#   rotation_size: 50 # 50MB
#   rotation_count: 7 # 7 days
#   level: "info"